### PR TITLE
refs #1683: fixed property name for access to logs

### PR DESCRIPTION
**Pull request by onedal88**

### CODE REVIEW

**Comment by jefleponot** [comment]
Thanks for contribution

@mickaelandrieu , agree to merge ?

**Comment by mickaelandrieu** [comment]
I need to review this in source code first.

**Comment by jefleponot** [comment]
all is ok for me

**Comment by mickaelandrieu** [comment]
Ok for me too (https://github.com/casperjs/casperjs/blob/master/modules/casper.js#L166)

Thank you for review and for contributions guys ;)

**Pull request merged**
