### PR TITLE
rebased setFieldValue/setFieldValueName/setFieldValueLabel functions from #1459"

### PR DESCRIPTION
**Pull request by jefleponot**
eslint corrections

jefleponot

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@jefleponot would you mind to use a more explicit label ? Something like "rebased setFieldValue/setFieldValueName/setFieldValueLabel functions from #1459"

**Comment by jefleponot** [comment]
Hi @mickaelandrieu ,

I'm quite sorry, I can't manage to keep the same PR number (#1459)
And I don't like duplicated code on clientutils.js so I would like to improve that.

:racehorse:

**Comment by mickaelandrieu** [comment]
@jefleponot ok, don't forget to use "relevant" commit labels, this help us understand what is going on.

history

**Comment by istr** [comment]
I would merge this -- @BIGjuevos could you do a second review and merge it if ok? @mickaelandrieu wants this for quite a while...

**Comment by mickaelandrieu** [comment]
@istr mainly because we have merged docs for this before ... :D this contribution is valuable :+1:

**Comment by BIGjuevos** [comment]
I like it.  Merging.

**Comment by istr** [comment]
Thanks @jefleponot for the work and @BIGjuevos for merging. :-)

**Comment by jefleponot** [comment]
Hi @BIGjuevos , @istr , @mickaelandrieu 

you were too fast for merging. I had to refactor fews functions to simplify them and make them more readable before to go on holiday. but I lacked time.

Could I commit on the same branch ? or Do I have to use another PR ?
jef

**Comment by istr** [comment]
> Do I have to use another PR

Another PR, please. Thank you.

**Pull request merged**
