### PR TITLE
Fix "navigation to parent frame" crashs

### PR DESCRIPTION
**Pull request by jefleponot**
With PhantomJS < 2.1.1, frame _parent navigation crashes : https://github.com/ariya/phantomjs/issues/13042

### CODE REVIEW

**Comment by jefleponot** [comment]
@mickaelandrieu , to me mind this PR is mature and successful.
it will be very useful for phantomJS engines < 2.1.1

Do you agree to rebase ?

Now I will work on casperjs.exe compilation :+1: 
And also try to insert phantomjs 2.5.0 beta into travis CI .

**Comment by mickaelandrieu** [comment]
@jefleponot why do you want me to rebase? Also, I need more time to review this contribution.

Mickaël

**Comment by mickaelandrieu** [comment]
Do you want me to squash commits on merge? :)

**Comment by jefleponot** [comment]
It is nice to show in a first commit the tests code (that run with errors)
and with a second commit to show how it can be solved :-) 

After we can merge or squash before merging ...

**Comment by mickaelandrieu** [comment]
ok I can do it :+1:

**Comment by mickaelandrieu** [comment]
Sorry, misrode your comment

**Comment by jefleponot** [comment]
I think this PR is really mature and very useful so I merge it. 
Thanks for all notices

**Pull request merged**
