### PR TITLE
fixed signatures of event callbacks in docs

### PR DESCRIPTION
**Pull request by zzanzare**
refs #1704
refs #1328

### CODE REVIEW

**Comment by jefleponot** [comment]
??? it is not correct

**Comment by zzanzare** [comment]
in which sense?

If it's about the travis failure, I believe my commit could not have possibly caused this error: `The command "npm install -g eslint@v1.10.1" failed and exited with 1` - can we somehow re-trigger the travis build?

**Comment by jefleponot** [comment]
I'm sorry but you contribution has no sense
Javascript doesn't require as first parameter the caller so ... i don't understand your work.

Could you please add explanations ?

**Comment by zzanzare** [comment]
well i was playing with casper, following the documentation here: http://docs.casperjs.org/en/latest/modules/casper.html#onresourcereceived and I needed to use these event handlers. And by dumping the function arguments I found out they are receiving the Casper object as the first argument, contrary to what the documentation said. So I fixed the documentation according to the actual behavior. See the tickets, they describe the problems quite clearly. It's just doc fix, no code change

**Comment by jefleponot** [comment]
@zzanzare,

Thanks you for all yours explanations, I haven't understood that your are talking about casper.options.
You are totally right. Very goof job.

What do you think about the "onAlert" documentation ?
if you can fix it too as you would be nice :smile: 

Regards (before merge)

Could you please, after squash all commits and re-base for merging branch.

**Comment by zzanzare** [comment]
@jefleponot ok I added also onAlert, and rebased

**Comment by jefleponot** [comment]
@zzanzare , great job,

@mickaelandrieu @BIGjuevos ready to merge ?

**Comment by mickaelandrieu** [comment]
👍 go for it!

**Pull request merged**
