### PR TITLE
Add cookbook example for passing in parameters into tests

### LINKED ISSUE #1787: How do I pass custom arguments into a testscript
Hi, is there a way for me to pass custom arguments to a casperjs test? 

I want to pass in the base url for the page I'm testing.

I tried using envitonment variables but process.env was not available. What is the suggested way?

### PR DESCRIPTION
**Pull request by tarjei**
Fixes #1787 :)

### CODE REVIEW

**Comment by jefleponot** [comment]
@tarjei 

What do you think of http://docs.casperjs.org/en/latest/cli.html ?

**Comment by tarjei** [comment]
Looks good - but I didn't find that text when looking :) Maybe I should add a link in the cookbook text?

**Comment by jefleponot** [comment]
a new PR is welcome :smile:

**Comment by tarjei** [comment]
Updated.

**Comment by tarjei** [comment]
Also - why isn't casper.once() documented?

**Comment by jefleponot** [comment]
Casper is extended by EventEmitter (an old version) and it has never been documented ... :cry:

**Comment by tarjei** [comment]
Ah :)

**Pull request merged**
