### PR TITLE
fixed travis build icon

### PR DESCRIPTION
**Pull request by the872**
made icon .svg to support retina displays and removed redundant stuff too

### CODE REVIEW

**Comment by the872** [comment]
make sure to [ci skip] on merge

**Comment by istr** [comment]
Sorry, builds are failing due to broken upstream package handling. We are catering for that and restart your build when it is fixed.

**Comment by mlalpho** [comment]
@the872, you'll need to at least merge the .travis.yml, but I'd recommended rebasing and merging your changes with the current master before resending the PR

**Comment by the872** [comment]
@mlalpho, but there are no conflicts?

**Comment by mlalpho** [comment]
@the872: judging from the travis ci build log, it's still reading in the old links to the slimerjs download repo, whereas, in the new ci configuration it should be reading from casperjs/slimerjs-builds. see #1635 -- after you've made those changes travis ci builds should pass and then someone from the casperjs team will take it from there :+1:

**Comment by BIGjuevos** [comment]
I've restarted the build.  Let's see how it does this time.

**Comment by istr** [comment]
I would like to propose to merge this without rebase and without passing test. It is trivial and does not touch any code, whatsoever. The merged build is about 99% to succeed.

**Comment by BIGjuevos** [comment]
I'm convinced by @istr and concur.

Merging.

**Pull request merged**
