### PR TITLE
fixed wrong element bounds, refs #1592

### PR DESCRIPTION
**Pull request by imdmitrykravchenko**
fix issue #1592

### CODE REVIEW

**Comment by jefleponot** [comment]
Very good job @imdmitrykravchenko

**Comment by istr** [comment]
I like it, too. Please add a test that demonstrates #1592 and shows that this PR fixes it. Thank you.

**Comment by jefleponot** [comment]
@imdmitrykravchenko , could you please add a test and rebase
Regards

**Comment by kensoh** [comment]
Archiving PR using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now. These PRs are from 1-5 years ago but there just hasn't been maintainers to continue the work.

**Pull request closed without merging**
