### PR TITLE
refactoring the setFieldValue-enhancement PR

### PR DESCRIPTION
**Pull request by jefleponot**
@Macek007 had proposed a nice enhancement but it was not properly integrated in existent code.

This PR normalizes methods (names, parameters), optimizes threats and simplifies maintenance of
clientutils.js ( keeping all BC ).

Regards
Jef

### CODE REVIEW

**Comment by jefleponot** [comment]
Hi @istr, @mickaelandrieu @paazmaya @BIGjuevos ,

Everything looks OK , could you please have a look ?

**Comment by istr** [comment]
Looks good at first sight, please give me time over next weekend to review properly.

**Comment by jefleponot** [comment]
@istr, do you have any objection for merging ?

**Comment by istr** [comment]
I am ok to merge this, tests pass and this improves the code of a recently added functionality.
Ping @mickaelandrieu @paazmaya @BIGjuevos.

**Comment by jefleponot** [comment]
@BIGjuevos , @mickaelandrieu , we need your agreement for merge this PR.

**Comment by mickaelandrieu** [comment]
Was already OK,  just forgot to say it!  Thanks @jefleponot and @istr

**Pull request merged**
