### PR TITLE
Rework of the casperjs.org website

### PR DESCRIPTION
**Pull request by BIGjuevos**
Basically, pulled in bootstrap.  Many things from free CDNs.  Deleted everything else except the minimalistic (figured we don't need the cruft).

In support of: #1532 

Pinging @istr, @mickaelandrieu, and @n1k0 for this one for their input.  There anything I missed or am legally required to add?

The markup is at: https://github.com/BIGjuevos/casperjs/blob/54cbb14524e6ebbb8bfd8e02929d371b53a45bb8/index.html

The style is at:https://github.com/BIGjuevos/casperjs/blob/54cbb14524e6ebbb8bfd8e02929d371b53a45bb8/css/casper.css

Full Site

Responsive Site:

### CODE REVIEW

**Comment by istr** [comment]
:+1: Maybe, instead of the large twitter button:
- de-emphasize twitter (is it that significant?)
- re-add the download button / link the latest tarball

Something along the lines of

UIkit start

**Comment by mickaelandrieu** [comment]
Hi, it's nice ! I don't like green but It's totaly personal ahaha ^^

**Comment by BIGjuevos** [comment]
> Hi, it's nice ! I don't like green but It's totaly personal ahaha ^^

Totally understand.  I tried to find the least offensive green possible.  My thoughts were, everything else is blue (we don't need another blue thing), red makes people angry, and when tests pass they are green.

So I went with it.  Seems to work out.

> Maybe, instead of the large twitter button:

The space felt like it was missing something, so I put the twitter button there.  Your idea feels much more appropriate.

**Comment by istr** [comment]
> I tried to find the least offensive green possible.

Success! I don't care that much about the color (it is ok), but the improvement on the overall structure is great -- so let us try to get this out if nobody has major objections. Ping @n1k0 @hexid @paazmaya.

**Comment by n1k0** [comment]
This is great and I love the new green. r+ from me

**Comment by n1k0** [comment]
I'm just wondering if we couldn't get colored syntax... and probably using a better monospace font like Consolas or Monaco by default.</nits>

**Comment by BIGjuevos** [comment]
> I'm just wondering if we couldn't get colored syntax... and probably using a better monospace font like Consolas or Monaco by default.

Easy Enough

Remaining items before pushing this thing live:
- [ ] Colored Syntax
- [ ] Better monospace font
- [ ] Swap out twitter button with download button and addition git info below.

**Comment by n1k0** [comment]
Also we should probably talk about that Paypal button at some point. What should I do with these twelve dollars?

Just kidding, had about $600 in 4y, but at some point I'd love reinjecting this money for community things, so if you have ideas and are willing to take care of it, just ask.

**Comment by BIGjuevos** [comment]
> Just kidding, had about $600 in 4y, but at some point I'd love reinjecting this money for community things, so if you have ideas and are willing to take care of it, just ask.

**Comment by mickaelandrieu** [comment]
@n1k0 we may probably contact Jeremy Forveille ? I can participate to have "corporate" assets (logo, fonts, etc...) and new design proposal. What do you think ?

**Comment by mickaelandrieu** [comment]
@n1k0 I want also buy some stickers but im my dreaming plans, you keep the money and we ask some companies to pay for xD

**Comment by n1k0** [comment]
I was actually more thinking of server costs, domain names (I realize I'm paying the .org), maybe goodies, things like that. But keep ideas coming :)

**Comment by mickaelandrieu** [comment]
@BIGjuevos I just forgot we already have CasperJS logo assets :) http://docs.casperjs.org/en/latest/credits.html#logo

**Comment by BIGjuevos** [comment]
> I just forgot we already have CasperJS logo assets :)
http://docs.casperjs.org/en/latest/credits.html#logo

I'm all on board for things like stickers, pins, t-shirts, little ghost plushes.

**Comment by BIGjuevos** [comment]
I'm going to give a few day grace period before I clobber the existing gh-pages branch and replace with this for any last minute feedback.  Pinging for awareness: @istr @mickaelandrieu @paazmaya @n1k0 

Desktop:


Mobile:

**Comment by mickaelandrieu** [comment]
@BIGjuevos it's really great!

**Comment by n1k0** [comment]
Yeah, looks great @BIGjuevos. We should land this.

**Comment by istr** [comment]
Yes, very nice. @BIGjuevos Thanks a lot. :-)

**Comment by jefleponot** [comment]
very good job :clap:

**Comment by BIGjuevos** [comment]
OK, no major objections were brought up, and it's not like we can't change it in the future.  Merging.

**Comment by istr** [comment]
Nice... :clap: Thank you, @BIGjuevos 
Very busy time over here, so happy that you tackled that.

**Comment by BIGjuevos** [comment]
@istr It only took a few beers and a late night dose of boredom. 😀

**Pull request merged**
