### PR TITLE
 Handle flex and inline-flex for reading visible state

### PR DESCRIPTION
**Pull request by paazmaya**
Redone what got messed in #1136, for #1085

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
👍 ping @casperjs/contributors for one more vote :)

**Comment by BIGjuevos** [comment]
looks good :+1:

**Comment by mickaelandrieu** [comment]
@paazmaya I'd like to keep all contributions pushed from a fork, just noticed it was a branch from official repository if you don't mind :)

**Comment by paazmaya** [comment]
@mickaelandrieu sure thing.
Is this documented yet anywhere?

**Comment by mickaelandrieu** [comment]
@paazmaya no, if we all agree on this behavior, maybe can we add a note in wiki ? What do you think ?

**Comment by paazmaya** [comment]
Sure

**Pull request merged**
