### PR TITLE
refs #1694 - fix scroll problem in captureSelector and captureBase64

### PR DESCRIPTION
**Pull request by mehdishojaei**
Fixed Issue #1694

### CODE REVIEW

**Comment by jefleponot** [comment]
Thanks for contribution

@mickaelandrieu, do you agree to rebase ?

**Comment by mickaelandrieu** [comment]
:+1:  go for it @jefleponot !

**Comment by mirzazeyrek** [comment]
Any ETA for adding it into npm ?

**Comment by jefleponot** [comment]
ETA ?

**Comment by mirzazeyrek** [comment]
Sorry may be it's not a proper usage "estimated time of arrival" :) 

I meant when it will be possible to update npm version :)

**Pull request merged**
