### PR TITLE
closes #1543

### LINKED ISSUE #1543: Test exists for #1535
Please ensure that a test exists for #1535

### PR DESCRIPTION
**Pull request by BIGjuevos**
adds tests for --xunit to check for output

@istr - tests, for your pleasure. Also, I hate python.

### CODE REVIEW

**Comment by istr** [comment]
oh yes -- python. *sigh*

**Comment by istr** [comment]
@mickaelandrieu I would merge this. Please do so if you like this PR. Thank you.

**Comment by mickaelandrieu** [comment]
Humm,  as tests sounds good I merge.  I don't use python too :D

**Comment by mickaelandrieu** [comment]
BTW thanks @BIGjuevos

**Pull request merged**
