### PR TITLE
closes #548

### LINKED ISSUE #548: onLoadError callback, load.failed event not working as expected/documentation very thin
while trying to find a way to count the number of >400 <599 http status responses, i noticed that onLoadError and load.failed are not behaving like i expected after reading the documentation.

this event:
```javascript
/* Emitted when PhantomJS’ WebPage.onLoadFinished event callback has been called and failed.*/
casper.on('load.failed', function errorhandler() {
    casper.echo('load.faild');
});
```
Is not fired if http://mypage.com/index.html contains images that generate a 404
is not fired if http://mypage.com/doesnotexit.html is 404
is only fired if http://doesnotexist (non-existing domain) is faild

```javascript
/*A function to be called when a requested resource cannot be loaded*/
casper.options.onLoadError = function (casper, resource) {
    console.echo("loaderror");
    console.log('received: ' + resource.url + ' ' + resource.status);
};
```
this is, in the 3 cases stated above, never be fired. same for onLoadFinished, no idea what these events are for.

```javascript
/*Emitted when any resource has been received.*/
casper.on('resource.received', function(resource) {
    casper.echo(resource.url + ' ' + resource.status);
});
```
this also fires if the resource is 404, or the request is completely failed (like http://doesnotexist). for me as external user, the resource is not received, so this event should not fire.

even if my complains above are invalid and are the expected result, the events need to be more documented. it is not clear when they are fired. for each resource-related event, make clear if it related to a main resource (page browsed to) or for subresources (i.e. images on that page) or both. and also how resource errors work (404 does not seem to be an error for casperjs/phantomjs).

### PR DESCRIPTION
**Pull request by BIGjuevos**
Adds a note in the cookbook about how to build something like this.

### CODE REVIEW

**Comment by istr** [comment]
imho it is better not to reference gists but to copy the gist into https://github.com/casperjs/casperjs/tree/master/samples and reference that instead.

gists tend to disappear at some point in the future leaving broken references that may stay unnoticed for a long time.

**Comment by BIGjuevos** [comment]
@istr, that't funny.  I had the exact same opposite thought.  "Why copy paste it when we have a link to a really nice gist with comments."

I'll pull it in as well, and reference the gist since it has lots of comments.

**Comment by BIGjuevos** [comment]
@istr - Updated.

**Comment by istr** [comment]
> I'll pull it in as well, and reference the gist since it has lots of comments.

:+1: I am angry at broken gist links very often, so I'd always prefer to keep a copy. Merging.

**Pull request merged**
