### PR TITLE
+ dependency: PhantomJS

### PR DESCRIPTION
**Pull request by zaz**
Issue #1719

### CODE REVIEW

**Comment by jefleponot** [comment]
Hi @zaz ,

Could you explain me what is "phantomjs-prebuilt" and what is dependency ?
I don't know how does node module works ...

**Comment by jefleponot** [comment]
Yes but CasperJS can also work with slimerJS , is there any dependencies for slimerJS ?

**Comment by zaz** [comment]
@jefleponot: This PR doesn't add any dependencies for SlimerJS.

If that is the case, then this PR is inappropriate and an alternative method should be considered for ensuring the user installs PhantomJS or SlimerJS.  This could either be a message displayed to the user after install, or two new packages, _CasperJS_Phantom_ and _CasperJS_Slimer_ that wrap this package and the respective dependency.

**Comment by jefleponot** [comment]
@zaz, thank for your explanations.
I hope that CasperJS could be also compatible with web extensions (Chrome and Firefox)

**Pull request closed without merging**
