### PR TITLE
Removed mention of CoffeeScript support.

### PR DESCRIPTION
**Pull request by 46bit**
Hi. CasperJS [removed CoffeeScript support](https://github.com/ariya/phantomjs/issues/12410) in line with PhantomJS. However, the website is still advertising running CoffeeScript files. This removes that mention.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
this concerns phantomjs2 and phantomjs2 support is planned into casperjs2

**Comment by jefleponot** [comment]
great

And my LinkText PR .................please

**Comment by paazmaya** [comment]
@46bit could you update this PR against https://github.com/n1k0/casperjs/tree/phantomjs-2 ?

**Comment by istr** [comment]
We will retain BC for 1.1 and 2.0 will probably not come up in the near future. Please create a new PR against the 2.0 branch and update like @paazmaya advised. Thanks a lot.

**Comment by istr** [comment]
Lots of discussions down the road meanwhile.
I am :+1: to merge this now. @46bit Would you mind rebasing it?
@mickaelandrieu @BIGjuevos I would "just do this" now.

**Comment by mickaelandrieu** [comment]
@istr ok to me (sorry, I'm realy busy with PrestaShop and I dont use CasperJS :/ )

**Comment by BIGjuevos** [comment]
I'm OK to merge this.  We just need to get the conflicts resolved.

**Comment by istr** [comment]
@mickaelandrieu similar situation over here... But wanted to keep my promise and get back to CasperJS "somewhere mid June"... :-)

**Comment by 46bit** [comment]
Hi @istr. Fun to see this getting picked up after so long. I've rebased to the master branch. 

I grepped the docs for remaining mentions of CoffeeScript. There are a few warnings about it being gone in 2.0.0 which is great - presumably they should remain for the time being. There are also two remaining sections on using CoffeeScript:

* http://docs.casperjs.org/en/latest/extending.html#using-coffeescript
* The warning on http://docs.casperjs.org/en/latest/writing_modules.html

Both might be relevant to people writing in CoffeeScript but I'm not sure they still belong in CasperJS docs.

**Comment by kensoh** [comment]
Archiving PR using **ARCHIVE** label as CasperJS, like PhantomJS, is not actively maintained for now. These PRs are from 1-5 years ago but there just hasn't been maintainers to continue the work.

**Pull request closed without merging**
