### PR TITLE
sendKeys fixes with content-editables

### PR DESCRIPTION
**Pull request by Llorx**
This PR makes `{ reset: true }` to work with content-editables.

### CODE REVIEW

**Comment by Llorx** [comment]
This is weird. .11 faisl in a lot of different tests that I've not touched :-/

**Comment by jefleponot** [comment]
@Llorx very good job
please rebase your PR before  merged it.

**Comment by Llorx** [comment]
Well, sorry if this is a dumb question, but seems that my path-1 branch is created from the last casperjs branch, so don't know what you say about rebase.

I've created the branch and modified the files via web. Don't know if I have to do something with a git client.

**Comment by jefleponot** [comment]
Fix reset "content-editables=true"  fields on "casper.sendKeys" calls.

**Comment by timabbott** [comment]
Any idea when this fix will make it into a release?  We're running into this problem with the Zulip project, and I'd love to be able to just upgrade.

**Comment by jefleponot** [comment]
Hi @timabbott 

Have you test the master code ? If there are no trouble I will create a new release 1.4.4-2, okay ?

jef

**Comment by timabbott** [comment]
Yep!  It passes all of Zulip's tests (after I fixed one bug in the tests that is visible only with the new version).

**Comment by jefleponot** [comment]
@timabbott 

Thanks a lot

**Pull request merged**
