### PR TITLE
fix slimer.version

### PR DESCRIPTION
**Pull request by jefleponot**
utils.ltVersion(slimer.version, '0.10.0')

instead of

utils.ltVersion(phantom.version, '0.10.0')

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hum, I'm not sure that `slimer` variable exists the only engine variable is ``phantom`` and you should refers to it.

I think, we should rename ``phantom`` to ``engine`` but it's a lot of works for no big gain.

**Comment by jefleponot** [comment]
you are wrong.

https://docs.slimerjs.org/current/api/slimer.html

with slimerJS the variable phantom.version contains the version of PhantomJS to which SlimerJS is compatible (read-only)

So ((phantom.casperEngine === '**slimerjs**' &&  utils.ltVersion(**phantom.version, '0.10.0'**))
is totaly no sense

**Comment by mickaelandrieu** [comment]
Make sense then, but what is the value of `phantom.version` when slimerjs is used as the engine ?

**Comment by jefleponot** [comment]
slimerjs-0.8.4 => phantom.version equivalent to {"major":1,"minor":9,"patch":0}
slimerjs-0.8.5 => phantom.version equivalent to {"major":1,"minor":9,"patch":0}
slimerjs-0.9.6 => phantom.version equivalent to {"major":1,"minor":9,"patch":2}
slimerjs-0.10.0 => phantom.version equivalent to {"major":1,"minor":9,"patch":8}

**Comment by mickaelandrieu** [comment]
o_O wow.

:+1:  to me, thank you @jefleponot for hint this bug !

ping @casperjs/contributors for merge please :)

Mickaël

**Comment by BIGjuevos** [comment]
2 legit 2 quit :+1:

**Pull request merged**
