### PR TITLE
don't create unnecessary globals in bootstrap.js

### LINKED ISSUE #1730: bootrap.js is needlessly creating global variables
```js
var isFunction = function(o) {
  return 'function' === typeof o;
};
var bind;
var slice = [].slice;
var proto = Function.prototype;
var featureMap = {
  'function-bind': 'bind'
};
function has(feature) {
  var prop = featureMap[feature];
  return isFunction(proto[prop]);
}
```

### PR DESCRIPTION
**Pull request by bughit**
fixes #1730

### CODE REVIEW

**Comment by jefleponot** [comment]
Ok to merge
@mickaelandrieu 

@bughit , could you please rename the commit comment ?

**Comment by bughit** [comment]
@jefleponot Was it just the missing "in" or did you have something else in mind?

**Comment by jefleponot** [comment]
In fact, everything is ok. good job.
ready to merge

**Comment by mickaelandrieu** [comment]
Hello, looks good for me too :)

Thank you @bughit for contribution and @jefleponot for review

**Pull request merged**
