### PR TITLE
PR for #1844 - Possible EventEmitter memory leak - warning message and docs

### PR DESCRIPTION
**Pull request by djwales**
This is the pull request for issue #1844 

Changes as per issue. Modified the warning messages in modules/events.js when max listeners is exceeded. Also updated the online documentation to discuss the setMaxListeners function.

### CODE REVIEW

**Comment by jefleponot** [comment]
@djwales 

Very good works

Could you please rebase your PR from master and recommit it ?

    $  git rebase -i master

**Comment by jefleponot** [comment]
@djwales 

Everything you have done is ok
Travis Tests has failed because of a new travis configuration ... it will be a nice thing to stop testing the  oldest versions of SlimerJs.

Now do you know how to rebase all your PR ?

**Comment by djwales** [comment]
No, sorry. I tried running 

`git rebase -i master`

But the message just said _noop_ and it didn't list any commits. I created a fork of the casper repo and made my changes on master in my fork. I then created a pull request from my fork back to the casper repo.

**Comment by jefleponot** [comment]
@djwales 

okay

Please create a branch
    git checkout -b FixmemoryLeak
    git checkout master
    git reset --hard
   git checkout FixmemoryLeak
   git rebase -i master
   git push djwales FixmemoryLeak --force

**Comment by djwales** [comment]
@jefleponot 

I had to do it slightly differently. This is what I did (in my forked repo):

git checkout -b FixMemoryLeak
git checkout master
git reset --hard HEAD~3
git checkout FixMemoryLeak
git rebase -i master
\# I then saved the rebase file without modifying it. 
git push --set-upstream origin FixMemoryLeak
git checkout master
git push --force

I now have a branch in my forked repo called FixMemoryLeak with my three commits in it. My commits are no longer present on my master branch in my forked repo. Is this what you wanted?

I tried doing _git reset --hard_ as you suggested by it didn't remove anything and when I tried to rebase the FixMemoryLeak branch it said _noop_ again. I assumed you wanted me to remove my commits from master and put them onto a branch.

**Comment by jefleponot** [comment]
you have to type

    git checkout master
    git reset a30162945d79cce7a664b17b576a5271ef1d7d9f

**Comment by djwales** [comment]
@jefleponot 

I have done that but nothing has changed as far as I can see. Sorry if I am making a mess of this, this is my first open source PR so I am not 100% sure of the steps. I appreciate your help so far.

My [forked repo](https://github.com/djwales/casperjs) has two branches - master & FixMemoryLeak. The head of master is currently:

> a30162945d79cce7a664b17b576a5271ef1d7d9f - jefleponot - visible element can't be critical for click trigger

The head of FixMemoryLeak is currently: 

> 2f19e75509a26f3aa1182929b0373ea20336f77b - David - Fixed a typo in the online documentation - refs #1844

My branch contains my three commits whilst master is in sync with the main [casperjs/casperjs](https://github.com/casperjs/casperjs) repo.

When you asked me to _Rebase my PR from master and recommit it_, did I need to do anything else or just move my changes onto a branch?

Do I now need to create a new Pull Request from my branch? I have noticed that the PR is now closed which I am assuming is because I have moved the commits from master onto a branch.

**Comment by jefleponot** [comment]
@djwales 

You are totally right
With git, it is better to work always on a new branch to create a feature. When your code is stable and tests are all passed, you have just to merge all the commits of the branch (rebase mode) and propose a PR to project.

Closing your all PR and opening another one, is exactly the good way

**Comment by djwales** [comment]
Thanks @jefleponot.

I have created a new PR from my branch - #1848

**Pull request closed without merging**
