### PR TITLE
Exclude vector logo from npm package

### PR DESCRIPTION
**Pull request by betalb**
refs #1632 - Exclude ai, pdf and eps logo files from npm package

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@betalb would you mind to rebase your pull request ? Thank you

**Comment by betalb** [comment]
@mickaelandrieu rebased, ci is green now

**Comment by mickaelandrieu** [comment]
@betalb thanks!

@casperjs/contributors it's Ok to me, we need another :+1: here ;)

**Comment by BIGjuevos** [comment]
Looks good to me.

**Pull request merged**
