### PR TITLE
fix for evaluate function. in case if user passes one array argument …

### PR DESCRIPTION
**Pull request by Marshevskyy**
hey guys. here is a fix for evaluate function. in case if user passes one array argument with one object. evaluate converted this array to object instead return original array with one object.

example 

```
let mockArray = [];

//any actions
mockArray.push({
  name: 'casper'
});
casper.evaluate(function (arr) {
       //I expect that arr = [{name: 'casper'}]
       //but it returns {name:'casper'}
       //so my fix is for this case, to return [{name: 'casper'}] instead of {name:'casper'}
 }, mockArray);
```

### CODE REVIEW

**Comment by mlalpho** [comment]
Test might need to be updated for this one

**Comment by mlalpho** [comment]
I don't really know what's going on with Travis:

**Comment by mlalpho** [comment]
```
Resolving download.slimerjs.org (download.slimerjs.org)... 176.31.242.138

Connecting to download.slimerjs.org (download.slimerjs.org)|176.31.242.138|:80... connected.

HTTP request sent, awaiting response... 403 Forbidden

2016-06-13 13:34:55 ERROR 403: Forbidden.
```

**Comment by Marshevskyy** [comment]
yep, strange tests error

> The command "if [[ $ENGINE_ARCHIVE_URL == *.tar.bz2 ]]; then wget $ENGINE_ARCHIVE_URL --output-document=engine.tar.bz2; bunzip2 engine.tar.bz2; elif [[ $ENGINE_ARCHIVE_URL == *.tar.gz ]]; then wget $ENGINE_ARCHIVE_URL --output-document=engine.tar.gz; gunzip engine.tar.gz; elif [[ $ENGINE_ARCHIVE_URL == *.zip ]]; then wget $ENGINE_ARCHIVE_URL --output-document=engine.zip; else echo "Unsupported compression type for url $ENGINE_ARCHIVE_URL"; fi" failed and exited with 2 during .

**Comment by Marshevskyy** [comment]
is there any comment command, to run tests without "git push". I mean something like "github retest this please"

**Comment by mlalpho** [comment]
I honestly don't know enough about the setup to say one way or another. Might be possible if you or a team member signs in to Travis using github.. from what i can see there's no 'Rebuild' button

**Comment by Marshevskyy** [comment]
could anybody from casperjs team look into issue with failed build?

**Comment by mlalpho** [comment]
@BIGjuevos is on the case!  #1620 Thank ya

**Comment by istr** [comment]
@BIGjuevos seems like we need to do this... :-(

**Comment by istr** [comment]
@BIGjuevos would you mind moving your repo https://github.com/BIGjuevos/phantomjs-builds to https://github.com/casperjs/phantomjs-builds ? I created https://github.com/casperjs/slimerjs-builds and will populate it now.

**Comment by mlalpho** [comment]
@Marshevskyy this should be able to get mereged as #1620 is now closed. Please rebase and/or resend this PR so that Travis will pick it up :) :+1:

**Comment by Marshevskyy** [comment]
@mlalpho thanks. merging

**Comment by mlalpho** [comment]
Ping @BIGjuevos @istr @mickaelandrieu  can one of you look these changes over?

**Comment by jefleponot** [comment]
please rebase PR for merge procédure.

> git rebase -i master
with squash details

**Comment by jefleponot** [comment]
@mickaelandrieu another PR to merge, ok ?

**Comment by mickaelandrieu** [comment]
@Marshevskyy would you mind to reword the last commit label ?

**Comment by Marshevskyy** [comment]
hey @mickaelandrieu what do you mean? what is wrong with commit label?

**Comment by mickaelandrieu** [comment]
@Marshevskyy the commit named "dummy PR" doesnt help anyone to understand what is going on.

Also I saw you didnt rebase from master but pull, and you just create a merge commit... please [rebase](https://help.github.com/articles/syncing-a-fork/) and remove this merge commit.

Thank you

**Comment by Marshevskyy** [comment]
@mickaelandrieu.  ah gotcha. done

**Comment by mickaelandrieu** [comment]
@Marshevskyy Thank you :)

**Pull request merged**
