### PR TITLE
Creates getPlainText()

### PR DESCRIPTION
**Pull request by entrptaher**
In regards of https://github.com/casperjs/casperjs/issues/178
I had some problems because of the newline char at the end of the file. Should take note for future.

### CODE REVIEW

**Comment by entrptaher** [comment]
@BIGjuevos What happened to this pull request?

**Comment by istr** [comment]
I am ok to merge this. @entrptaher Could you please [squash this PR](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)?

**Comment by istr** [comment]
Ping @entrptaher: please squash the commits. If you're unsure how to do this, please add a comment here.
Ping @BIGjuevos @mickaelandrieu : if you are ok to merge without squash, please feel free to do so.
:-)

**Comment by mickaelandrieu** [comment]
@istr better: thanks to the new ``Squash`` option of github, I merge **and** squash it for @entrptaher :)

Thanks for contribution and for review !

**Comment by jefleponot** [comment]
it lacks the "getPlainText" documentation method ... snifffff

**Pull request merged**
