### PR TITLE
update new parameters for command line 

### PR DESCRIPTION
**Pull request by jefleponot**
@mlalpho, #1609

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
:+1:  this probably deserve a new release :)

**Comment by zachary-sierakowski** [comment]
:+1: I spent some time yesterday with an issue related to these parameters! A release for this would be great.

**Comment by jefleponot** [comment]
@mickaelandrieu, can you list all actions that we have to do to create a release ?

**Comment by mickaelandrieu** [comment]
@jefleponot I have no idea, I've never released this project /c @istr maybe share a doc I guess :)

**Comment by jefleponot** [comment]
@mickaelandrieu, :laughing: 
nice idea 1.1.4 : could we add it the "waitForRender" method ?

**Pull request merged**
